/*
 * Vehicle Enquiry Service Swagger
 * This is the CVS API for showing details of heavy goods vehicles and their associated test result.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package vott.dto;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * Brakes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-12T12:23:07.722Z[GMT]")
public class Brakes {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("brakeCodeOriginal")
  private String brakeCodeOriginal = null;

  @SerializedName("brakeCode")
  private String brakeCode = null;

  @SerializedName("dataTrBrakeOne")
  private String dataTrBrakeOne = null;

  @SerializedName("dataTrBrakeTwo")
  private String dataTrBrakeTwo = null;

  @SerializedName("dataTrBrakeThree")
  private String dataTrBrakeThree = null;

  @SerializedName("retarderBrakeOne")
  private String retarderBrakeOne = null;

  @SerializedName("retarderBrakeTwo")
  private String retarderBrakeTwo = null;

  @SerializedName("serviceBrakeForceA")
  private Integer serviceBrakeForceA = null;

  @SerializedName("secondaryBrakeForceA")
  private Integer secondaryBrakeForceA = null;

  @SerializedName("parkingBrakeForceA")
  private Integer parkingBrakeForceA = null;

  @SerializedName("serviceBrakeForceB")
  private Integer serviceBrakeForceB = null;

  @SerializedName("secondaryBrakeForceB")
  private Integer secondaryBrakeForceB = null;

  @SerializedName("parkingBrakeForceB")
  private Integer parkingBrakeForceB = null;

  public Brakes id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
    public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Brakes brakeCodeOriginal(String brakeCodeOriginal) {
    this.brakeCodeOriginal = brakeCodeOriginal;
    return this;
  }

   /**
   * Get brakeCodeOriginal
   * @return brakeCodeOriginal
  **/
    public String getBrakeCodeOriginal() {
    return brakeCodeOriginal;
  }

  public void setBrakeCodeOriginal(String brakeCodeOriginal) {
    this.brakeCodeOriginal = brakeCodeOriginal;
  }

  public Brakes brakeCode(String brakeCode) {
    this.brakeCode = brakeCode;
    return this;
  }

   /**
   * Get brakeCode
   * @return brakeCode
  **/
    public String getBrakeCode() {
    return brakeCode;
  }

  public void setBrakeCode(String brakeCode) {
    this.brakeCode = brakeCode;
  }

  public Brakes dataTrBrakeOne(String dataTrBrakeOne) {
    this.dataTrBrakeOne = dataTrBrakeOne;
    return this;
  }

   /**
   * Get dataTrBrakeOne
   * @return dataTrBrakeOne
  **/
    public String getDataTrBrakeOne() {
    return dataTrBrakeOne;
  }

  public void setDataTrBrakeOne(String dataTrBrakeOne) {
    this.dataTrBrakeOne = dataTrBrakeOne;
  }

  public Brakes dataTrBrakeTwo(String dataTrBrakeTwo) {
    this.dataTrBrakeTwo = dataTrBrakeTwo;
    return this;
  }

   /**
   * Get dataTrBrakeTwo
   * @return dataTrBrakeTwo
  **/
    public String getDataTrBrakeTwo() {
    return dataTrBrakeTwo;
  }

  public void setDataTrBrakeTwo(String dataTrBrakeTwo) {
    this.dataTrBrakeTwo = dataTrBrakeTwo;
  }

  public Brakes dataTrBrakeThree(String dataTrBrakeThree) {
    this.dataTrBrakeThree = dataTrBrakeThree;
    return this;
  }

   /**
   * Get dataTrBrakeThree
   * @return dataTrBrakeThree
  **/
    public String getDataTrBrakeThree() {
    return dataTrBrakeThree;
  }

  public void setDataTrBrakeThree(String dataTrBrakeThree) {
    this.dataTrBrakeThree = dataTrBrakeThree;
  }

  public Brakes retarderBrakeOne(String retarderBrakeOne) {
    this.retarderBrakeOne = retarderBrakeOne;
    return this;
  }

   /**
   * Get retarderBrakeOne
   * @return retarderBrakeOne
  **/
    public String getRetarderBrakeOne() {
    return retarderBrakeOne;
  }

  public void setRetarderBrakeOne(String retarderBrakeOne) {
    this.retarderBrakeOne = retarderBrakeOne;
  }

  public Brakes retarderBrakeTwo(String retarderBrakeTwo) {
    this.retarderBrakeTwo = retarderBrakeTwo;
    return this;
  }

   /**
   * Get retarderBrakeTwo
   * @return retarderBrakeTwo
  **/
    public String getRetarderBrakeTwo() {
    return retarderBrakeTwo;
  }

  public void setRetarderBrakeTwo(String retarderBrakeTwo) {
    this.retarderBrakeTwo = retarderBrakeTwo;
  }

  public Brakes serviceBrakeForceA(Integer serviceBrakeForceA) {
    this.serviceBrakeForceA = serviceBrakeForceA;
    return this;
  }

   /**
   * Get serviceBrakeForceA
   * @return serviceBrakeForceA
  **/
    public Integer getServiceBrakeForceA() {
    return serviceBrakeForceA;
  }

  public void setServiceBrakeForceA(Integer serviceBrakeForceA) {
    this.serviceBrakeForceA = serviceBrakeForceA;
  }

  public Brakes secondaryBrakeForceA(Integer secondaryBrakeForceA) {
    this.secondaryBrakeForceA = secondaryBrakeForceA;
    return this;
  }

   /**
   * Get secondaryBrakeForceA
   * @return secondaryBrakeForceA
  **/
    public Integer getSecondaryBrakeForceA() {
    return secondaryBrakeForceA;
  }

  public void setSecondaryBrakeForceA(Integer secondaryBrakeForceA) {
    this.secondaryBrakeForceA = secondaryBrakeForceA;
  }

  public Brakes parkingBrakeForceA(Integer parkingBrakeForceA) {
    this.parkingBrakeForceA = parkingBrakeForceA;
    return this;
  }

   /**
   * Get parkingBrakeForceA
   * @return parkingBrakeForceA
  **/
    public Integer getParkingBrakeForceA() {
    return parkingBrakeForceA;
  }

  public void setParkingBrakeForceA(Integer parkingBrakeForceA) {
    this.parkingBrakeForceA = parkingBrakeForceA;
  }

  public Brakes serviceBrakeForceB(Integer serviceBrakeForceB) {
    this.serviceBrakeForceB = serviceBrakeForceB;
    return this;
  }

   /**
   * Get serviceBrakeForceB
   * @return serviceBrakeForceB
  **/
    public Integer getServiceBrakeForceB() {
    return serviceBrakeForceB;
  }

  public void setServiceBrakeForceB(Integer serviceBrakeForceB) {
    this.serviceBrakeForceB = serviceBrakeForceB;
  }

  public Brakes secondaryBrakeForceB(Integer secondaryBrakeForceB) {
    this.secondaryBrakeForceB = secondaryBrakeForceB;
    return this;
  }

   /**
   * Get secondaryBrakeForceB
   * @return secondaryBrakeForceB
  **/
    public Integer getSecondaryBrakeForceB() {
    return secondaryBrakeForceB;
  }

  public void setSecondaryBrakeForceB(Integer secondaryBrakeForceB) {
    this.secondaryBrakeForceB = secondaryBrakeForceB;
  }

  public Brakes parkingBrakeForceB(Integer parkingBrakeForceB) {
    this.parkingBrakeForceB = parkingBrakeForceB;
    return this;
  }

   /**
   * Get parkingBrakeForceB
   * @return parkingBrakeForceB
  **/
    public Integer getParkingBrakeForceB() {
    return parkingBrakeForceB;
  }

  public void setParkingBrakeForceB(Integer parkingBrakeForceB) {
    this.parkingBrakeForceB = parkingBrakeForceB;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Brakes brakes = (Brakes) o;
    return Objects.equals(this.id, brakes.id) &&
        Objects.equals(this.brakeCodeOriginal, brakes.brakeCodeOriginal) &&
        Objects.equals(this.brakeCode, brakes.brakeCode) &&
        Objects.equals(this.dataTrBrakeOne, brakes.dataTrBrakeOne) &&
        Objects.equals(this.dataTrBrakeTwo, brakes.dataTrBrakeTwo) &&
        Objects.equals(this.dataTrBrakeThree, brakes.dataTrBrakeThree) &&
        Objects.equals(this.retarderBrakeOne, brakes.retarderBrakeOne) &&
        Objects.equals(this.retarderBrakeTwo, brakes.retarderBrakeTwo) &&
        Objects.equals(this.serviceBrakeForceA, brakes.serviceBrakeForceA) &&
        Objects.equals(this.secondaryBrakeForceA, brakes.secondaryBrakeForceA) &&
        Objects.equals(this.parkingBrakeForceA, brakes.parkingBrakeForceA) &&
        Objects.equals(this.serviceBrakeForceB, brakes.serviceBrakeForceB) &&
        Objects.equals(this.secondaryBrakeForceB, brakes.secondaryBrakeForceB) &&
        Objects.equals(this.parkingBrakeForceB, brakes.parkingBrakeForceB);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, brakeCodeOriginal, brakeCode, dataTrBrakeOne, dataTrBrakeTwo, dataTrBrakeThree, retarderBrakeOne, retarderBrakeTwo, serviceBrakeForceA, secondaryBrakeForceA, parkingBrakeForceA, serviceBrakeForceB, secondaryBrakeForceB, parkingBrakeForceB);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Brakes {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    brakeCodeOriginal: ").append(toIndentedString(brakeCodeOriginal)).append("\n");
    sb.append("    brakeCode: ").append(toIndentedString(brakeCode)).append("\n");
    sb.append("    dataTrBrakeOne: ").append(toIndentedString(dataTrBrakeOne)).append("\n");
    sb.append("    dataTrBrakeTwo: ").append(toIndentedString(dataTrBrakeTwo)).append("\n");
    sb.append("    dataTrBrakeThree: ").append(toIndentedString(dataTrBrakeThree)).append("\n");
    sb.append("    retarderBrakeOne: ").append(toIndentedString(retarderBrakeOne)).append("\n");
    sb.append("    retarderBrakeTwo: ").append(toIndentedString(retarderBrakeTwo)).append("\n");
    sb.append("    serviceBrakeForceA: ").append(toIndentedString(serviceBrakeForceA)).append("\n");
    sb.append("    secondaryBrakeForceA: ").append(toIndentedString(secondaryBrakeForceA)).append("\n");
    sb.append("    parkingBrakeForceA: ").append(toIndentedString(parkingBrakeForceA)).append("\n");
    sb.append("    serviceBrakeForceB: ").append(toIndentedString(serviceBrakeForceB)).append("\n");
    sb.append("    secondaryBrakeForceB: ").append(toIndentedString(secondaryBrakeForceB)).append("\n");
    sb.append("    parkingBrakeForceB: ").append(toIndentedString(parkingBrakeForceB)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
